version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - mongo-compose-network

  rabbitmq:
    image: beevelop/rabbitmq-stomp
    ports:
      - 5672:5672
      - 15672:15672
      - 15674:15674

networks:
  mongo-compose-network:
    driver: bridge
